# Generated by Django 5.2.1 on 2025-05-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_note_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
